### ISSUE TITLE
注释问题

### ISSUE THREAD

**Issue by qOeOp** [yeecode/MyBatisCN#2]
关于MapperMethod中resolveMappedStatement()方法的注释
@param declaringClass 操作方法所在的类。一般是映射接口本身，也可能是映射接口的子类<br>
 这里子类应该改作父类吧,interface A(amethod)--extend-->interface B(bmethod)，B的实现类应该实现a&b两个方法,如果namespace:B中只映射了b方法,不过A的实现类namespace:A实现了a方法,getMap(B.class).amethod因为B没实现，mybatis会找到父接口的实现类来实现吧。很喜欢yee的书,如指正有误,望回复

**Comment by yeecode** [comment]
假设A是父类，B是子类。

结合下面的递归部分的代码和你的第二段说明，可见，传入一个类B时，会去找类B及其父类，假设最终找到A。这一点应该是我们都认同的。

那这时，入参中传入的是B，即入参declaringClass是B。最终的映射接口为A。

**注释中要描述declaringClass，则它可能是A本身，也可能是A的子类。**

我们递归寻找了declaringClass 的父类（含自身），所以，declaringClass 是子类（含自身）。因此，注释应该是正确的。
