### ISSUE TITLE
不明的一个注释

### ISSUE THREAD

**Issue by cnzbq** [yeecode/MyBatisCN#3]
这个类 org.apache.ibatis.reflection.Reflector#pickBetterSetter

![image](https://user-images.githubusercontent.com/49929998/109762468-96c71700-7c2b-11eb-8a0f-a677ef6c2d35.png)
`if (paramType1.isAssignableFrom(paramType2)) {
      // 父类的那个为准
      return setter2;
    } else if (paramType2.isAssignableFrom(paramType1)) {
      return setter1;
    }`
这里应该是以子类的为准吧

**Comment by zlmgit** [comment]
是的，我看也是：父类.isAssignableFrom(子类)

**Comment by yeecode** [comment]
经过确认，这里注释确实出现了错误。逻辑为：
在paramType1是paramType2父类的情况下，返回setter2。即返回的是paramType2对应的setter，因此是以子类的那个为准。

谢谢两位的指正。
