### ISSUE TITLE
 PropertyCopier.copyBeanProperti描述错误

### ISSUE THREAD

**Issue by zlmgit** [yeecode/MyBatisCN#5]
文中写的是：
copyBeanProperties方法的工作原理非常简单：通过反射获取类的 所有属性，然后依次将这些属性值从源对象复制出来并赋给目标对象。 但是要注意一点，**该属性复制器无法完成继承得来的属性的复制，因为
getDeclaredFields方法返回的属性中不包含继承属性。**
这个是可以获得继承来的属性的，他循环复制属性后，最后会获取父类判空继续循环父类的属性进行赋值

**Comment by yeecode** [comment]
经过阅读，这里确实出现了错误。
在双重循环的外循环中，通过parent.getSuperclass()操作得到了父级，然后对父级也进行了遍历。因此copyBeanProperties确实可以完成父类中的属性的拷贝。

感谢您的悉心阅读，也您的指正。

同时，也将该处纰漏反馈给了出版社。将在后续的版本中改正该错误。

再次感谢您的指正！
也相信您的认真和努力一定会带来技术上的成长！
共勉！
